"""
Django settings for tryDjango project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd$98z9anh$-0ay4x%n^9dl%dh!)h8tpb05dq9*18i@5$6@%1hh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#Setting up Email and removing security from google (REMOVE DISPLAY CAPACTHA)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'amitsachdeva3677@gmail.com'
EMAIL_HOST_PASSWORD = 'amitkkp12'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


"""
Unlock The Google Captcha to start using Django
Search =>  DISPLAY UNLOCK CAPTCHA
"""



# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Third party apps on second place
    'crispy_forms',

    #My Apps on third place
    'newsletter'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'tryDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tryDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

#Static files can js, css files which contains code
#This place is where all files are finally collected (from staticfiles_dir or internal static files)
#It can be aws service or any cloud service or even part of project)
#It will happen during deployment
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static_and_media_files","static_root")
#"/var/www/example.com/static/"    #Deployement url for path of static files

#Directories where are keeping our static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static_and_media_files","static_files"),
]

#media can photos, any thing which we upload in forms
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static_and_media_files","media_root")


#Requirements for REGISTRATION
ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window; you may, of course, use a different value.
REGISTRATION_AUTO_LOGIN = True # Automatically log the user in.


#Crispy forms
CRISPY_TEMPLATE_PACK = 'bootstrap3'